/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lockerusu;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author Putera Nami Shiddieqy
 */
public class OrganizeLocker extends javax.swing.JFrame {

    /**
     * Creates new form Organize_Locker
     */
    public OrganizeLocker() {
        initComponents();
    }
    
    private String convertToTimeFormat(int durasi) {
        int hours = durasi / 3600;
        int minutes = (durasi % 3600) / 60;
        int seconds = durasi % 60;
        return String.format("%02d:%02d:%02d", hours, minutes, seconds);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Panel_Admin = new javax.swing.JLabel();
        LabelID = new javax.swing.JLabel();
        IDLokeryangInginDipinjam = new javax.swing.JTextField();
        LabelNIM = new javax.swing.JLabel();
        NIMpeminjam = new javax.swing.JTextField();
        LabelWakru = new javax.swing.JLabel();
        FieldJam = new javax.swing.JTextField();
        FieldMenit = new javax.swing.JTextField();
        FieldDetik = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        btnKembaliKeMonitorAdmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(133, 209, 99));

        jPanel2.setBackground(new java.awt.Color(252, 249, 249));

        Panel_Admin.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        Panel_Admin.setForeground(new java.awt.Color(13, 102, 118));
        Panel_Admin.setText("Pinjam Loker USU");

        LabelID.setText("ID Loker");

        IDLokeryangInginDipinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDLokeryangInginDipinjamActionPerformed(evt);
            }
        });

        LabelNIM.setText("NIM");

        NIMpeminjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NIMpeminjamActionPerformed(evt);
            }
        });

        LabelWakru.setText("Waktu Pemakaian");

        FieldJam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldJamActionPerformed(evt);
            }
        });

        FieldMenit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldMenitActionPerformed(evt);
            }
        });

        FieldDetik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldDetikActionPerformed(evt);
            }
        });

        jLabel1.setText(":");

        jLabel2.setText(":");

        btnSubmit.setBackground(new java.awt.Color(0, 0, 0));
        btnSubmit.setForeground(new java.awt.Color(245, 245, 245));
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Panel_Admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(NIMpeminjam, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelNIM, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelWakru, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(FieldJam, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FieldMenit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FieldDetik, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(IDLokeryangInginDipinjam, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)))
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(Panel_Admin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IDLokeryangInginDipinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelNIM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NIMpeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(LabelWakru)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FieldJam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FieldMenit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FieldDetik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSubmit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnKembaliKeMonitorAdmin.setBackground(new java.awt.Color(13, 103, 119));
        btnKembaliKeMonitorAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnKembaliKeMonitorAdmin.setText("Kembali");
        btnKembaliKeMonitorAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliKeMonitorAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(172, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(btnKembaliKeMonitorAdmin)
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnKembaliKeMonitorAdmin)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IDLokeryangInginDipinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDLokeryangInginDipinjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDLokeryangInginDipinjamActionPerformed

    private void FieldJamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldJamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldJamActionPerformed

    private void FieldMenitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldMenitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldMenitActionPerformed

    private void FieldDetikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldDetikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldDetikActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        String idLoker = IDLokeryangInginDipinjam.getText();
        String nim = NIMpeminjam.getText();
        int jam = Integer.parseInt(FieldJam.getText());
        int menit = Integer.parseInt(FieldMenit.getText());
        int detik = Integer.parseInt(FieldDetik.getText());
        int durasiInSeconds = jam * 3600 + menit * 60 + detik; // Durasi dalam detik
        String durasi = convertToTimeFormat(durasiInSeconds); // Konversi ke format TIME

        try (Connection conn = DatabaseConnection.getConnection()) {
            // Periksa apakah loker sudah terpakai
            String checkSql = "SELECT status FROM locker WHERE id = ?";
            PreparedStatement checkStmt = conn.prepareStatement(checkSql);
            checkStmt.setString(1, idLoker);

            ResultSet rs = checkStmt.executeQuery();
            if (rs.next()) {
                boolean status = rs.getBoolean("status");
                if (status) {
                    JOptionPane.showMessageDialog(this, "Loker ini sudah dipinjam. Pilih loker lain.");
                    return;
                }
            } else {
                JOptionPane.showMessageDialog(this, "ID Loker tidak valid.");
                return;
            }

            // Hitung waktu selesai
            String calculateFinishTimeSql = "SELECT ADDTIME(NOW(), ?) AS waktu_selesai";
            PreparedStatement calculateStmt = conn.prepareStatement(calculateFinishTimeSql);
            calculateStmt.setString(1, durasi);

            ResultSet calculateRs = calculateStmt.executeQuery();
            String waktuSelesai = null;
            if (calculateRs.next()) {
                waktuSelesai = calculateRs.getString("waktu_selesai");
            }

            // Update tabel locker
            String updateLokerSql = "UPDATE locker SET status = ?, nim = ?, waktu_sisa = ? WHERE id = ?";
            PreparedStatement updateLokerStmt = conn.prepareStatement(updateLokerSql);
            updateLokerStmt.setBoolean(1, true); // true berarti loker terpakai
            updateLokerStmt.setString(2, nim);
            updateLokerStmt.setString(3, durasi); // Simpan durasi dalam format TIME
            updateLokerStmt.setString(4, idLoker);

            updateLokerStmt.executeUpdate();

            // Insert ke tabel locker_history
            String insertHistorySql = "INSERT INTO locker_history (NIM_user, locker_id, durasi, waktu_mulai, waktu_selesai) VALUES (?, ?, ?, NOW(), ?)";
            PreparedStatement insertHistoryStmt = conn.prepareStatement(insertHistorySql);
            insertHistoryStmt.setString(1, nim);
            insertHistoryStmt.setString(2, idLoker);
            insertHistoryStmt.setString(3, durasi);
            insertHistoryStmt.setString(4, waktuSelesai); // Masukkan waktu selesai

            insertHistoryStmt.executeUpdate();

            JOptionPane.showMessageDialog(this, "Loker berhasil dipinjam!");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void NIMpeminjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NIMpeminjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NIMpeminjamActionPerformed

    private void btnKembaliKeMonitorAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliKeMonitorAdminActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new MonitoringAdmin().setVisible(true);
    }//GEN-LAST:event_btnKembaliKeMonitorAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrganizeLocker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrganizeLocker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrganizeLocker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrganizeLocker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrganizeLocker().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FieldDetik;
    private javax.swing.JTextField FieldJam;
    private javax.swing.JTextField FieldMenit;
    private javax.swing.JTextField IDLokeryangInginDipinjam;
    private javax.swing.JLabel LabelID;
    private javax.swing.JLabel LabelNIM;
    private javax.swing.JLabel LabelWakru;
    private javax.swing.JTextField NIMpeminjam;
    private javax.swing.JLabel Panel_Admin;
    private javax.swing.JButton btnKembaliKeMonitorAdmin;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
